### ISSUE TITLE
pas-arch-tests v19.06_API0.9: val_nvmem_read failed. Error=0x80 for (SUITE=PROTECTED_STORAGE / SUITE=CRYPTO, tgt_dev_apis_stdc)

### ISSUE THREAD

**Issue by simonqhughes** [ARM-software/psa-arch-tests#115] opened 2019-09-12 13:38 UTC
Summary
=======

PSA Storage and PSA crypto test binaries for the tgt_dev_apis_stdc target fail with what appears to be a test framework bug. On running the binary the following error is reported:

```
simhug01@e113506-lin:/data/2303/20190910/psa-arch-test3/psa-arch-tests/api-tests/build-ps$ ./psa-arch-tests-ps
  	val_nvmem_read failed. Error=0x80
```

Investigation suggests a bug reading the binary file generated from the target file and that the problem is with:

```
/data/2303/20190910/psa-arch-test3/psa-arch-tests/api-tests/val/nspe/val_peripherals.c:
status = val_target_get_config(TARGET_CONFIG_CREATE_ID(GROUP_MEMORY,
            MEMORY_NVMEM, 0), 
            (uint8_t **)&memory_desc,
            (uint32_t *)sizeof(memory_desc_t));
```

which calls:

```
status = pal_nvmem_read_ns(memory_desc->start, offset, buffer, size);
psa-arch-test3/psa-arch-tests/api-tests/platform/targets/tgt_dev_apis_stdc/nspe/common/pal_driver_ns_intf.c
    if (nvmem_check_bounds(base, offset, size) != PAL_STATUS_SUCCESS)
    // this is whats failing: 
    static int nvmem_check_bounds(addr_t base, uint32_t offset, int size)
    {
          if (base != NVMEM_BASE)
          {
              printf("\tNVMEM_BASE=%lu, %x\n", base, NVMEM_BASE);
              return PAL_STATUS_ERROR;
          }
```

With the above printf() trace added (and other pal_nvmem_read_ns() trace) the output becomes:

```
  simhug01@e113506-lin:/data/2303/20190910/psa-arch-test3/psa-arch-tests/api-tests/build-ps$ ./psa-arch-tests-ps 	
    NVMEM_BASE=4398046511104, 0
  	pal_nvmem_read_ns. status=0x80
  	val_nvmem_read failed. Error=0x80
```

Indicating that base (i.e. memory_desc->start) is a bogus value. I understand the value should be 0 as specified by this config in the tgt_dev_apis_stdc/target.cfg:

```
    // In this implementation we don't actually use NV memory - we don't support
    // tests that require process or system restarts so NV memory isn't required.
    // The implementation just uses an array in memory.
    nvmem.num =1;
    nvmem.0.start = 0x0;
    nvmem.0.end = 0x400; // 1KiB
    nvmem.0.permission = TYPE_READ_WRITE;
```

Details: How to Reproduce the Error
==============================

I'm working to evaluate the psa-arch-test PSA storage test support which has been added (v19.06_API0.9 + changes). The same problem can be reproduced using 2 different methods:
A. Build a SUITE=PROTECTED_STORAGE test binary and run it.
B. Build a SUITE=CRYPTO test binary and run it. This can demonstrated with Vikas's fork (see later).

Method A: SUITE=PROTECTED_STORAGE Tests
=======================================

This is the procedure I use to run the PSA_PROTECTED_STORAGE tests

0. Create a workspace under subdir psa-arch-test3 as follows:
```
    psa-arch-test3/
      mbedtls-test                    // clone of project for main.c
      psa-arch-test                   // clone of the psa-arch-test
      psa_trusted_storage_linux       // clone of psa_trusted_storage_linux
```

The clone of psa-arch-test is created from this fork/branch:
  
```
    git clone git@github.com:jainvikas8/psa-arch-tests.git -b linux-target-support-workaround
```
  
which has mbed-crypto related changes on top of v19.06_API0.9.
  
The clone of mbedtls-test is just to get a boilerplate main.c for building tgt_dev_apis_stdc psa-arch-test binary.  For reference this is the main.c so you can reproduce without access to mbedtls-test:

```
      /*
       * Copyright (c) 2019 ARM Ltd.
       *
       * SPDX-License-Identifier: Apache-2.0
       */
      
      void val_entry(void);
      
      int main(int argc, char**argv)
      {
        val_entry();
        return 0;
      }
```

1. Build psa_trusted_storage_linux by cd into dir and typing make.

2. Build the ps-arch-test main.o boilerplate code:

```
    gcc -Wall -Werror -c -o ./mbedtls-test/resources/psa-arch-tests/main.o ./mbedtls-test/resources/psa-arch-tests/main.c
```

3. Make a psa-arch-tests test binary which includes the protected storage tests. to do this you have to follow the next steps.

4. Copy over the mbed-os storage target support into tgt_dev_apis_stdc.

```
cp -fR platform/targets/tgt_dev_apis_mbedos_fvp_mps2_m4/npse/protected_storage platform/targets/tgt_dev_apis_stdc/npse/
```

5. Edit platform/targets/tgt_dev_apis_mbedos_fvp_mps2_m4/target.cmake to enable the PS and ITS suite support by taking the following into tgt_dev_apis_stdc/target.cmake:

```
  if(${SUITE} STREQUAL "PROTECTED_STORAGE")
  	list(APPEND PAL_SRC_C_NSPE
  		${PSA_ROOT_DIR}/platform/targets/${TARGET}/nspe/protected_storage/pal_protected_storage_intf.c
  	)
  endif()
  if(${SUITE} STREQUAL "INTERNAL_TRUSTED_STORAGE")
  	list(APPEND PAL_SRC_C_NSPE
  		${PSA_ROOT_DIR}/platform/targets/${TARGET}/nspe/internal_trusted_storage/pal_internal_trusted_storage_intf.c
  	)
  endif()
```

6. Make a build dir 
```
    cd /data/2303/20190910/psa-arch-test3/psa-arch-tests/api-tests/
    mkdir build-ps
    cd build-ps
```

7. Use cmake to generate build tree

```
    simhug01@e113506-lin:/data/2303/20190910/psa-arch-test3/psa-arch-tests/api-tests/build-ps$ cmake ../ -DTOOLCHAIN=HOST_GCC -DTARGET=tgt_dev_apis_stdc -DSUITE=PROTECTED_STORAGE -DPSA_INCLUDE_PATH  -DCPU_ARCH=armv7m
```
  
this generates val_nspe.a, test_combine.a, pal_nspe.a. (Its a puzzle as to why -DCPU_ARCH=armv7m needs to be specified for the stdc target. Perhaps this can be fixed too?)

8. Link the psa-arch-test-ps binary from the *.a generated in the previous step, and the main.o:

```
    gcc -o psa-arch-tests-ps ../../../mbedtls-test/resources/psa-arch-tests/main.o ./dev_apis/protected_storage/test_combine.a ./val/val_nspe.a ./platform/pal_nspe.a ./dev_apis/protected_storage/test_combine.a ../../../psa_trusted_storage_linux/lib/libpsastorage.so
```

Note to self: put psa_trusted_storage_linux changes into repo so psa-arch-test-ps doen't have missing symbol problem i.e. add missing API function stubs.

Method B: SUITE=CRYPTO Tests
=============================

The following script can also be used  can be used to reproduce this problem:

```
#!/bin/sh

# This script helps to run the psa-arch-tests using mbed crypto library on linux environment.
# It patches, builds, links and runs the test to prove PSA complainance of crypto library. 

# Comment or uncomment neccessary repo to run the test script

git clone git@github.com:jainvikas8/psa-arch-tests.git -b linux-target-support-workaround
git clone git@github.com:ARMmbed/mbedtls-test.git -b dev/jainvikas8/automate-psa
git clone git@github.com:ARMmbed/mbed-crypto.git -b development

# Build the crypto library as position independent code.
make -C ./mbed-crypto

# Build the test script
gcc -Wall -Werror -c -o ./mbedtls-test/resources/psa-arch-tests/main.o ./mbedtls-test/resources/psa-arch-tests/main.c

# Make a build directory
mkdir ./psa-arch-tests/api-tests/build
cd ./psa-arch-tests/api-tests/build

# Configure build
cmake ../ -G"Unix Makefiles" -DTOOLCHAIN=HOST_GCC -DTARGET=tgt_dev_apis_stdc -DSUITE=CRYPTO \
    -DPSA_INCLUDE_PATHS=`readlink -f ../../../mbed-crypto/include` -DCPU_ARCH=armv7m

cmake --build .

# Link main.o together with the test libs to create an executable
# The mbed-crypto library which was built should be used here
gcc -o psa-arch-crypto-tests ./../../../mbedtls-test/resources/psa-arch-tests/main.o \
    ./dev_apis/crypto/test_combine.a ./val/val_nspe.a ./platform/pal_nspe.a ./dev_apis/crypto/test_combine.a \
    ./../../../mbed-crypto/library/libmbedcrypto.a

# Run
./psa-arch-crypto-tests
```

The attached log psa-arch-test_build_log_20190912_1606.txt shows the output from running the above script. The last line produces this output:

```
	val_nvmem_read failed. Error=0x80

Entering standby.. 
```

i.e. it shows the same error as Method A.

[psa-arch-test_build_log_20190912_1606.txt](https://github.com/ARM-software/psa-arch-tests/files/3606184/psa-arch-test_build_log_20190912_1606.txt)

**Comment by jainvikas8** [comment] 2019-09-16 10:09
@kotegowder Since PSA test suite has a requirement of Nvmem to preserve things across the boot
The input comes from the respective target.cfg file, therefore I tried the change in target.cfg for the new target **tgt_dev_apis_stdc**, seem to end with the same error.
`nvmem.0.start = 0x10;`

**Comment by jaypit02** [comment] 2019-09-16 10:26
Hi @simonqhughes ,

+++
Indicating that base (i.e. memory_desc->start) is a bogus value. I understand the value should be 0 as specified by this config in the tgt_dev_apis_stdc/target.cfg:
+++

As you mentioned, memory_desc->start is 4398046511104 (0x40000000000). It seems, it does 64 bit read and return the following two location values. 
nvmem.0.start = 0x0; [31:0]=0x00000000
nvmem.0.end = 0x400; [63:32]=0x400

As of now, PSA test suite complies for v7m/v8m targets which are 32 bit. And we considered addr_t to unit32_t typecast. (pal_common.h)

But it seems, tgt_dev_apis_stdc is updated to use uintptr_t as addr_t which can make pointer to be 64 bit. It can be the root cause of the failure.

tgt_dev_apis_stdc/nspe/common/pal_common.h:
typedef uintptr_t           addr_t;

There can be two solution to this:

1. Revert the type cast change. typedef uin32_t           addr_t;
2. Change all pointers to 64 bit. 

Out of these two, option(1) looks more trivial in given point of time. And option(2) is more ideal solution but involves lot of effort.

**Comment by jainvikas8** [comment] 2019-09-16 10:43
> But it seems, tgt_dev_apis_stdc is updated to use uintptr_t as addr_t which can make pointer to be 64 bit. It can be the root cause of the failure.
> 
> tgt_dev_apis_stdc/nspe/common/pal_common.h:
> typedef uintptr_t addr_t;
> 
> There can be two solution to this:
> 
> 1. Revert the type cast change. typedef uin32_t           addr_t;

Considering the above observation, I think it should be possible, but we will get a warning for sure
as mentioned here - https://github.com/ARM-software/psa-arch-tests/pull/113#issuecomment-525689756. 

Have tried the Option (1) and it passes through the following error point.

Option (2) seems that right way, but I don't know the effects on other targets?
So are we planning to move to 64-bit in the near future?
>As of now, PSA test suite complies for v7m/v8m targets which are 32 bit. And we considered addr_t to unit32_t typecast. (pal_common.h)

**Comment by jaypit02** [comment] 2020-02-27 09:57
Closing this as the issue is fixed by setting nvmem.0.end to zero as the target doesn't use the the nvmem field. This is already been merged.

**Closed by jaypit02** 2020-02-27 09:57 UTC
