### ISSUE TITLE
PSA Arch crypto test get wrong test number on AN521 

### ISSUE THREAD

**Issue by edison-ai** [ARM-software/psa-arch-tests#169] opened 2020-03-26 10:22 UTC
The expected total test number should be 61, but the actual test number is 62 this test.

The test information is this:
board: FVP an521
Configuration: ConfigPsaApiTest, ConfigPsaApiTestIPC and ConfigPsaApiTestIPCTfmLevel2
build type: Release
TF-M commit: b70f6243d92c623d1bcb109ff79e887a9bc3b0a4
PSA arch commit: v20.03_API1.0, 3d986e72d9e084bb45763849699718f474fb10ba

**Comment by kotegowder** [comment] 2020-05-06 12:10
Hi Edison,

The issue is not seen with latest TF-M changes.

Hence closing the issue.

**Closed by kotegowder** 2020-05-06 12:10 UTC
